# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - findepenApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --verbosity normal
        continue-on-error: false

      - name: dotnet publish
        run: dotnet publish -c Release -o ./publish --verbosity normal
        continue-on-error: false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EFDB04B281AD441BA81F00E5F0C3371F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_15F96DB94A644022BA9EF2B3F5610356 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B6F3A03B26214DBFBB32FEF27798B4D1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "findepenApi"
          slot-name: "Production"
          package: .

      - name: Run database migrations
        run: |
          echo "Database migrations will be handled by the application startup"
          echo "Ensure connection string is properly configured in Azure App Service"

      - name: Validate deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          echo "Deployment validation complete"
